name: Frontend Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Get code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 21.7.1

      - name: Install pnpm
        run: npm install -g pnpm@9.11.0

      - name: Install dependencies
        run: cd client && pnpm install --frozen-lockfile

      - name: Run semantic-release
        id: release
        run: cd client && pnpm exec semantic-release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          title: 'chore(release): ${{ steps.release.outputs.nextRelease.version }} [skip ci]'
          body: |
            ### ${{ steps.release.outputs.nextRelease.version }}

            Automated PR created by the Frontend Release GitHub Action.

          commit-message: 'chore(release): ${{ steps.release.outputs.nextRelease.version }} [skip ci]'
          base: main
          branch: release/${{ steps.release.outputs.nextRelease.version }}
