name: Frontend Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, 'chore(release):') }} # Skip if already pushed by the release process

    steps:
      - name: Get code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 21.7.1

      - name: Install pnpm
        run: npm install -g pnpm@9.11.0

      - name: Install dependencies
        run: cd client && pnpm install --frozen-lockfile

      - name: Run semantic-release
        run: cd client && pnpm exec semantic-release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Set Tag
        id: tag
        run: echo "tag=$(git describe --tags $(git rev-list --tags --max-count=1))" >> $GITHUB_OUTPUT

      - name: Extract version from tag
        id: version
        run: |
          tag=${{ steps.tag.outputs.tag }}
          version=${tag#client-v} # Remove 'client-v' prefix
          echo "version=${version}" >> $GITHUB_OUTPUT

      - name: Update package.json
        run: |
          version=${{ steps.version.outputs.version }}
          jq ".version = \"${version}\"" client/package.json > tmp.$$.json && mv tmp.$$.json client/package.json

      - name: Format with Prettier
        run: cd client && pnpm run prettier

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          title: 'chore(release): ${{ steps.tag.outputs.tag }}'
          body: |
            ### ${{ steps.tag.outputs.tag }}

            Automated PR created by the Frontend Release workflow.

          commit-message: 'chore(release): ${{ steps.tag.outputs.tag }}'
          base: main
          branch: release/${{ steps.tag.outputs.tag }}
