name: Prettify Client
on:
  pull_request:
    branches:
      - develop
      - main
    paths:
      - 'client/**' # Only trigger if there are changes in the client directory

permissions:
  contents: write

jobs:
  prettify:
    runs-on: ubuntu-latest

    steps:
      - name: Set up client
        uses: ./.github/actions/setup-client
        with:
          node_version: 21.7.1

      - name: Commit changes
        run: |
          cd client
          git config --local user.name "GitHub Action"
          git config --local user.email "action@github.com"
          git add .
          git commit -m "Apply Prettier formatted changes" || echo "No changes to commit"

          # Pull the latest changes before pushing
          git pull --rebase origin ${{ github.head_ref }} || echo "No changes to pull"

          # Push the changes
          git push origin HEAD:${{ github.head_ref }}
