name: Prettify Client
on:
  pull_request:
    branches:
      - develop
jobs:
  prettify:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Format with Prettier
        run: npm run prettier
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply Prettier formatted changes
          branch: ${{ github.head_ref }}
