name: Prettify Client

on:
  pull_request:
    branches:
      - develop
      - main
    paths:
      - 'client/**' # Only trigger if there are changes in the client directory

permissions:
  contents: write

jobs:
  setup:
    uses: ./.github/workflows/setup-client.yml

  prettify:
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: Format with Prettier
        run: cd client && npm run prettier

      - name: Commit changes
        run: |
          cd client
          git config --local user.name "GitHub Action"
          git config --local user.email "action@github.com"
          git add .
          git commit -m "Apply Prettier formatted changes" || echo "No changes to commit"

          # Pull the latest changes before pushing
          git pull --rebase origin ${{ github.head_ref }} || echo "No changes to pull"

          # Push the changes
          git push origin HEAD:${{ github.head_ref }}
