name: Test Client

on:
  pull_request:
    branches:
      - develop
      - main
    paths:
      - 'client/**' # Only trigger if there are changes in the client directory

jobs:
  setup:
    uses: ./.github/workflows/setup-client.yml

  build:
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: Run tests from Vitest
        run: cd client && npm run test
